# Generated by Django 3.1.7 on 2021-04-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodandquantity',
            name='recipe_unity',
            field=models.CharField(default='g', max_length=20, verbose_name="unité de mesure de l'ingrédient pour la recette"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodandquantity',
            name='quantity',
            field=models.CharField(max_length=100, verbose_name="quantitee de l'ingredient"),
        ),
    ]
