# Generated by Django 3.2 on 2021-05-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210426_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorierecipe',
            name='image_active',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/pictures', verbose_name='image active de la categorie'),
        ),
        migrations.AddField(
            model_name='categorierecipe',
            name='image_not_active',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/pictures', verbose_name='image non active de la categorie'),
        ),
    ]
