# Generated by Django 3.2 on 2021-04-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210412_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categorie',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categorie',
            field=models.ManyToManyField(to='recipe.CategorieRecipe', verbose_name='categorie de la recette'),
        ),
    ]
