# Generated by Django 3.2 on 2021-05-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210507_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodandquantity',
            name='food_purchase_unity',
            field=models.CharField(choices=[('Null', 'Not defined'), ('Cuillère à soupe', 'Cuillère à soupe'), ('Cuillère à café', 'Cuillère à café'), ('Cl', 'Centilitre'), ('Gr', 'Gramme'), ('Unité', 'Unité'), ('Pincée', 'Pincée')], default='Not defined', max_length=35, verbose_name="unité de mesure de l'ingrédient pour la liste d'achats"),
        ),
        migrations.AlterField(
            model_name='foodandquantity',
            name='recipe_unity',
            field=models.CharField(choices=[('Null', 'Not defined'), ('Cuillère à soupe', 'Cuillère à soupe'), ('Cuillère à café', 'Cuillère à café'), ('Cl', 'Centilitre'), ('Gr', 'Gramme'), ('Unité', 'Unité'), ('Pincée', 'Pincée')], max_length=20, verbose_name="unité de mesure de l'ingrédient pour la recette"),
        ),
    ]
