# Generated by Django 3.2 on 2021-04-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20210415_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='categorie',
            new_name='categories',
        ),
    ]
