# Generated by Django 3.2.3 on 2021-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20210510_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_translate',
            field=models.BooleanField(default=False, verbose_name='recette traduite ?'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name_en',
            field=models.CharField(max_length=55, null=True, unique=True, verbose_name='nom de la recette en anglais'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_en',
            field=models.TextField(null=True, verbose_name='étapes de préparation de la recette en anglais'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tip_en',
            field=models.TextField(null=True, verbose_name='astuces divers en anglais'),
        ),
    ]
