# Generated by Django 3.2 on 2021-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20210420_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodandquantity',
            name='food_purshase_unity',
            field=models.CharField(choices=[('Null', 'Not defined'), ('CaS', 'Cuillère à soupe'), ('CaC', 'Cuillère à café'), ('CL', 'Centilitre'), ('GR', 'Gramme')], default='Not defined', max_length=35, verbose_name="unité de mesure de l'ingrédient pour la liste d'achats"),
        ),
        migrations.AlterField(
            model_name='foodandquantity',
            name='recipe_unity',
            field=models.CharField(choices=[('Null', 'Not defined'), ('CaS', 'Cuillère à soupe'), ('CaC', 'Cuillère à café'), ('CL', 'Centilitre'), ('GR', 'Gramme')], max_length=20, verbose_name="unité de mesure de l'ingrédient pour la recette"),
        ),
    ]
