# Generated by Django 3.2 on 2021-04-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20210420_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodandquantity',
            old_name='food_purshase_quantity',
            new_name='food_purchase_quantity',
        ),
        migrations.RemoveField(
            model_name='foodandquantity',
            name='food_purshase_unity',
        ),
        migrations.AddField(
            model_name='foodandquantity',
            name='food_purchase_unity',
            field=models.CharField(choices=[('Null', 'Not defined'), ('CaS', 'Cuillère à soupe'), ('CaC', 'Cuillère à café'), ('CL', 'Centilitre'), ('GR', 'Gramme'), ('U', 'Unité')], default='Not defined', max_length=35, verbose_name="unité de mesure de l'ingrédient pour la liste d'achats"),
        ),
        migrations.AlterField(
            model_name='foodandquantity',
            name='recipe_unity',
            field=models.CharField(choices=[('Null', 'Not defined'), ('CaS', 'Cuillère à soupe'), ('CaC', 'Cuillère à café'), ('CL', 'Centilitre'), ('GR', 'Gramme'), ('U', 'Unité')], max_length=20, verbose_name="unité de mesure de l'ingrédient pour la recette"),
        ),
    ]
