version: '3.7'

services:
  web:
    build: ./
    command: pipenv run python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env