version: '3.7'

services:
  web:
    build: ./
    restart: always
    command: pipenv run gunicorn feedeasyform_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/feedeasyform_project/settings/staticfiles
      - media_volume:/usr/src/app/feedeasyform_project/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # A CHANGER SUR LE SERVEUR EN PROD
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=name_database
      # --------------------------------

  nginx-proxy:
    container_name: nginx-proxy
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/feedeasyform_project/settings/staticfiles
      - media_volume:/usr/src/app/feedeasyform_project/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - .env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  