version: '3.7'

services:
  web:
    build: ./
    restart: always
    command: pipenv run gunicorn feedeasyform_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/feedeasyform_project/settings/staticfiles
      - media_volume:/usr/src/app/feedeasyform_project/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # A CHANGER SUR LE SERVEUR EN PROD
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=name_database
      # --------------------------------

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/feedeasyform_project/settings/staticfiles
      - media_volume:/usr/src/app/feedeasyform_project/media
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume:
  