# Generated by Django 3.0.5 on 2020-04-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='FoodQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=45)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('prepare_duration', models.CharField(max_length=45)),
                ('cooking_time', models.CharField(max_length=45)),
                ('step', models.TextField()),
                ('price_scale', models.CharField(max_length=45)),
                ('level', models.CharField(max_length=45)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Categorie')),
                ('food_quantity', models.ManyToManyField(to='planning.FoodQuantity')),
            ],
        ),
    ]
