# Generated by Django 3.1.5 on 2021-03-04 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nom du jour de la semaine')),
                ('date', models.DateField(verbose_name='date de ce jour')),
            ],
        ),
        migrations.CreateModel(
            name='MealsPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='nom du repas')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_friday', to='planning.day', verbose_name='vendredi')),
                ('monday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_monday', to='planning.day', verbose_name='lundi')),
                ('saturday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_saturday', to='planning.day', verbose_name='samedi')),
                ('sunday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_sunday', to='planning.day', verbose_name='dimanche')),
                ('thursday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_thursday', to='planning.day', verbose_name='jeudi')),
                ('tuesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_tuesday', to='planning.day', verbose_name='mardi')),
                ('wednesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_wednesday', to='planning.day', verbose_name='mercredi')),
            ],
        ),
        migrations.CreateModel(
            name='DayMealsPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.day', verbose_name='jour de la semaine')),
                ('meal_per_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.mealsperday', verbose_name='type de repas')),
                ('recipes', models.ManyToManyField(to='recipe.Recipe', verbose_name='recettes présentent dans le repas')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='meals_per_day',
            field=models.ManyToManyField(through='planning.DayMealsPerDay', to='planning.MealsPerDay', verbose_name='type de repas dans la journée'),
        ),
    ]
