# Generated by Django 3.0.7 on 2020-12-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryplan',
            name='description',
            field=models.TextField(default='desc', verbose_name='courte description'),
            preserve_default=False,
        ),
    ]
