# Generated by Django 3.1.5 on 2021-03-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='date',
        ),
    ]
