# Generated by Django 3.0.7 on 2020-12-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_dietaryplan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dietary_plan',
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_plan',
            field=models.ManyToManyField(to='planning.DietaryPlan', verbose_name='régime alimentaire de la recette'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='season',
        ),
        migrations.AddField(
            model_name='recipe',
            name='season',
            field=models.ManyToManyField(to='planning.Season', verbose_name='saison de la recette'),
        ),
    ]
