# Generated by Django 3.0.5 on 2020-04-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20200428_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Categorie', verbose_name='Nom de la categorie de la recette'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(max_length=45, verbose_name='Temps de cuisson'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='food_quantity',
            field=models.ManyToManyField(to='planning.FoodQuantity', verbose_name='Aliment et quantité'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='level',
            field=models.CharField(choices=[('easy', 'facile'), ('meduim', 'moyen'), ('chef', 'chef')], max_length=45, verbose_name='Difficultée'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prepare_duration',
            field=models.CharField(max_length=45, verbose_name='Temps de préparation'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='price_scale',
            field=models.CharField(choices=[('low', 'petit budget'), ('meduim', 'moyen budget'), ('high', 'gros budget')], max_length=45, verbose_name='Fouchette de prix'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='step',
            field=models.TextField(verbose_name='Étapes de la recette'),
        ),
    ]
