# Generated by Django 3.0.5 on 2020-04-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20200428_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Nom de la catégorie'),
        ),
    ]
