# Generated by Django 3.0.5 on 2020-04-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_auto_20200428_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Ustensile de cuisine')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='utensil',
            field=models.ManyToManyField(to='planning.Utensil', verbose_name='Ustensile de cuisine'),
        ),
    ]
