# Generated by Django 3.0.5 on 2020-05-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200430_1153'),
        ('planning', '0006_auto_20200430_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodquantity',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='Aliment'),
        ),
        migrations.AlterField(
            model_name='foodquantity',
            name='quantity',
            field=models.CharField(max_length=45, verbose_name="Quantité de l'aliment"),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='level',
            field=models.CharField(choices=[('easy', 'facile'), ('medium', 'moyen'), ('chef', 'chef')], max_length=45, verbose_name='Difficultée'),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='name',
            field=models.CharField(max_length=45, verbose_name="Nom de l'ustensile de cuisine"),
        ),
    ]
