# Generated by Django 3.1.7 on 2021-04-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='energie',
            field=models.CharField(max_length=15, null=True, verbose_name='energie (kcal/100g)'),
        ),
    ]
