# Generated by Django 3.0.5 on 2020-04-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='food',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Group', verbose_name="Groupe de l'aliment"),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=45, verbose_name="Nom de l'aliment"),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=45, verbose_name="Nom du groupe de l'aliment"),
        ),
    ]
