# Generated by Django 3.2.4 on 2021-07-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_allergie'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='nom du rayon')),
                ('image_active', models.ImageField(blank=True, null=True, upload_to='recipe/pictures', verbose_name='image active du rayon de magasin')),
                ('image_not_active', models.ImageField(blank=True, null=True, upload_to='recipe/pictures', verbose_name='image non active du rayon de magasin')),
            ],
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='store_rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.storerack', verbose_name='rayon de magasin du groupe alimentaire'),
        ),
    ]
