# Generated by Django 3.1.7 on 2021-04-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_food_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_code',
            field=models.IntegerField(null=True, unique=True, verbose_name='code aliment'),
        ),
    ]
