# Generated by Django 3.2.4 on 2021-07-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210701_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storerack',
            name='image_active',
            field=models.ImageField(blank=True, null=True, upload_to='store_rack/pictures', verbose_name='image active du rayon de magasin'),
        ),
        migrations.AlterField(
            model_name='storerack',
            name='image_not_active',
            field=models.ImageField(blank=True, null=True, upload_to='store_rack/pictures', verbose_name='image non active du rayon de magasin'),
        ),
    ]
